permissionsNeedsAuth:
    - 'bungeecord.command.server'
    - 'bungeecord.command.list'
    - 'bungeecord.command.alert'
    - 'bungeecord.command.end'
    - 'bungeecord.command.ip'
    - 'bungeecord.command.reload'
    - 'bungeecord.command.send'
    - 'servermanager.use'
isAuthMeSessionEnabled: false
